version: '3'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      ENV APP_PORT: 8080
      ENV APP_SERVICE_ID: say_hello
      ENV APP_VERSION: 0.1.0
      ENV APP_COMPONENT_ID: http_say_hello
      ENV APP_COMPONENT_TYPE: backend
  healthcheck:
    build: .docker/healthcheck
    networks:
      - backend
  prometheus:
    build: .docker/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000

networks:
  backend:

